apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config-prod
  namespace: amul
data:
  default.conf: |
    # Logs to stdout/stderr
    error_log  /dev/stderr warn;

    log_format json_analytics escape=json '{'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"request":"$request",'
        '"status": "$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"request_time":"$request_time",'
        '"http_referrer":"$http_referer",'
        '"http_user_agent":"$http_user_agent",'
        '"upstream_response_time":"$upstream_response_time"'
    '}';

    map $request_uri $loggable {
        default 1;
        ~^/stub_status 0;
    }

    access_log /dev/stdout json_analytics if=$loggable;

    # Log format matching the exporter configuration
    log_format prometheus '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
    
    # Write to shared volume for the sidecar exporter
    access_log /var/log/nginx/access.log prometheus if=$loggable;

    ############################################
    # API.PROD.AMULAI.IN - HTTP -> HTTPS
    ############################################
    server {
        listen 80;
        server_name api.prod.amulai.in;
        location / {
            return 301 https://$host$request_uri;
        }
    }

    ############################################
    # API.PROD.AMULAI.IN - HTTPS
    ############################################
    server {
        listen 443 ssl;
        server_name api.prod.amulai.in;

        ssl_certificate     /etc/ssl/.prod.amulai.in/tls.crt;
        ssl_certificate_key /etc/ssl/.prod.amulai.in/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        client_max_body_size 50M;
        resolver 10.96.0.10 valid=30s;

        location / {
            set $prod_api_upstream http://amul-oan-api.amul-prod.svc.cluster.local:8000;
            proxy_pass $prod_api_upstream;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    ############################################
    # METRICS
    ############################################
    server {
        listen 8080;
        server_name localhost;
        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
